kind: pipeline
name: drone-kubernetes-image-updater

steps:
  - name: put_tags
    image: alpine:3.9
    commands:
      - echo -n "$DRONE_TAG,latest" > .tags
    when:
      event:
      - tag  

  - name: docker-image
    image: plugins/docker
    settings:
       username:
         from_secret: DOCKER_USERNAME
       password:
         from_secret: DOCKER_PASSWORD
       repo:
         from_secret: DOCKER_REPO
       dockerfile: Dockerfile
    when:
      event:
       - tag
